canonical/cn.ubuntu.com

templates/templates/footer.html
Added a bug link to the footer
Check that link is correct and looks good in all viewports
=> add github bug link to footer

templates/download/index.html
- Added the latest 16.10 row to the download page
- Changed naming some db includes to logical
- Pull down and run setup and develop
- You need in import the download json to get the database changes
``` bash
wget https://gist.githubusercontent.com/anthonydillon/b14e385d4b4f9aec9ae6c2ab8e446a08/raw/b5dfb2fc8a17dc01d731f791e0f5f6468579f9f5/download.json
curl https://gist.githubusercontent.com/anthonydillon/9511e9c4edd98a55041e0eae1fabc88b/raw/557713b50b8e18ab98c86671d7280d2bc0203618/import-download-json.py | docker-compose run web ./manage.py shell
```
- https://docs.google.com/document/d/1b8pXcsMPTzu5dXiG7qKBSvYzwV1aawQ12M4mzsOnQfM/edit
=> Add the latest row to the download page

templates/news/2017/03/16/orange-pi-snap-store.html
Update news story UTM params
See that the new news story's links have UTM tags added.
=> update UTM links

templates/templates/base.html
Add OS to the operating system navigation items
- Pull code
- Run `make run`
- Check the first 2 and 4th navigation item has OS
Card https://trello.com/c/rBV4eboU/2839-add-os-to-the-navigation-items
Brief https://docs.google.com/document/d/1jk_uZ0Qd2EuyqHAHxrpvK07QIagilGJdXEV_iUtP6qo/edit?ts=58d003a3
=> Add OS to the navigation items

templates/desktop/index.html
=> update laptop image

run
QA
--
``` bash
./run clean
./run  # See it download django modules from t'internet
./run clean
./run  # See it install django modules from cache
```
=> Use latest run script, including pip cache

templates/templates/404.html, templates/templates/500.html
Update markup on 404 / 500 pages to Vanilla v1
- Run code
- Check 400 / 500 pages for layout
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/63
=> Update markup on 404 / 500 pages to Vanilla v1

templates/download/index.html
- Converted /download section of the site to Vanilla v1 styles
- Pull code
- View download page on http://0.0.0.0:8010/download
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/68
=> Converted /download section of the site to Vanilla v1 styles

static/sass/styles.scss, templates/server/index.html
Server visual design review
- Pull code
- Run `./run`
- Go to http://0.0.0.0:8010/server
- Check the design tweaks in the attached issue have been complete
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/166
=> Server visual design review

static/sass/styles.scss, templates/desktop/index.html
Desktop visual design review
- Pull code
- Run `./run`
- Go to http://0.0.0.0:8010/desktop
- Check the design tweaks in the attached issue have been complete
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/164
=> Desktop visual design review

static/sass/custom/_ubuntu_intro.scss, templates/index.html, templates/takeovers/_hackathon.html
Homepage visual design review
- Pull code
- Run `./run`
- Go to http://0.0.0.0:8010/
- Check the design tweaks in the attached issue have been complete
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/162
=> Homepage visual design review

static/sass/styles.scss, templates/internet-of-things/index.html
IoT design review tweaks
Check fixes against checklist in #163
Fixes #163
=> IoT design review tweaks

templates/cloud/index.html
- Add links to h3 headers
- Pull code
- Check against checklist on #170 
Fixes #170
=> /cloud design tweaks

package.json, templates/templates/base.html, yarn.lock
Add autoprefixer to build toolchain to fix external link icons
- View home page at http://0.0.0.0:8010/
- Verify external link icons display correctly
=> Add autoprefixer to build toolchain

static/sass/styles.scss, templates/download/index.html
- Addressed /download design tweaks
- Pull code
- Check against checklist on #171 
Fixes #171
=> /download design tweaks

Dockerfile, requirements.txt, webapp/wsgi.py
Add the docker file and update wsgi settings import.
- Run "docker build -t beta --build-arg COMMIT_ID=`git rev-parse HEAD`"
- Run `docker run -p 80:80 beta`
_Make sure nothing is listening to port 80_
- Go to http://localhost
=> Add docker file

templates/about/index.html, templates/cloud/index.html, templates/contact/index.html, templates/containers/index.html, templates/desktop/index.html, templates/download/index.html, templates/internet-of-things/index.html, templates/news/index.html, templates/server/index.html
Added page titles to each template.
Click through the pages and see that each page has a title that makes sense.
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/208
=> Add page titles

templates/desktop/index.html, templates/index.html
1. Remove old event banner
2. Add a new BIB report campaign
=> BIB report

templates/cloud/index.html, templates/index.html, templates/server/index.html
[Add new K8s webinar
Fix some issues]
=> k8s webinar

templates/templates/base.html
* Use correct GTM id to actually receive events from the website
=> Update to standard GTM

templates/templates/footer.html
Update the footer template so the year is calculated dynamically.
- `./run` to start the development server
- Browse the website and make sure year is showing as the current year.
=> Make footer date dynamic

package.json, static/sass/custom/_ubuntu_intro.scss
Updated the sass-lint command to recursively lint all SASS directories.
Fix a couple of SASS errors
- `./run`
- Verify styling looks good.
=> Fix SASS errors

renovate.json
As we've done with developer.ubuntu.com, docs.snapcraft.io and blog.ubuntu.com.
=> Renovate: group minor updates

templates/server/index.html
Update the 19.04 server features copy
- Read the new copy and make sure it makes sense.
- Check the link works.
=> Update the 19.04 server features copy

templates/blog/index.html
- Removes a duplicated ID
- removes unnecessary class
- `./run` and make
=> Removes duplicated ID and unnecessary class

requirements.txt, static/js/latest-news.js, templates/index.html, templates/shared/_latest-news.html, webpack.config.js
DEPENDS ON https://github.com/canonical-web-and-design/cn.ubuntu.com/pull/315/files
- Adds the latest new widget to china
Fixes https://github.com/canonical-web-and-design/base-squad/issues/482
- `./run` and make sure that the latest news are displayed correctly
- click on a link and confirm that you read the news article on the page
=> Latest news widget

static/js/latest-news.js, templates/blog/article.html, templates/shared/_latest-news.html
- Updates english strings with chinese versions
=> Translates english strings

templates/about/index.html, templates/cloud/index.html, templates/contact/index.html, templates/containers/index.html, templates/desktop/index.html, templates/download/index.html, templates/internet-of-things/index.html, templates/server/index.html, templates/templates/base.html, templates/templates/footer.html
- Fixed a number of issues in moving from vanilla 1 to 2
- download the branch
- visually check the site
=> Add vanilla 2.0 fixes for the footer and other components

requirements.txt, webapp/settings.py
Add local rss feed
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8010/blog/feed
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Test that the feed only has Chinese content
Fixes #336
=> Add local rss feed

static/js/latest-news.js
- Display articles on index page
- Make sure the latest articles are displayed on [http://0.0.0.0:8010/](http://0.0.0.0:8010/)
Fixes #338 
=> Display articles on index page

templates/download/index.html, templates/server/index.html
=> 19.10 release

templates/internet-of-things/index.html
More 404s fixes.
- `./run`
- http://localhost:8010/internet-of-things
Fixes #365
=> Fix more 404s

templates/templates/base.html
Updated GTM code to one just for cn.u.c, not u.c's
- See that the code is now GTM-MCKGLV
=> Update GTM code

releases.yaml, templates/download/index.html, templates/server/index.html, webapp/app.py
Replace 18.04, 19.10, etc... with releases.yaml variables
1. Download the branch
2. ./run
3. See that /download looks and acts right with all the release variables replaced
=> Replace 18.04, 19.10, etc... with releases.yaml variables

templates/about/index.html, templates/engage/vmware-to-openstack.html, templates/index.html, templates/takeovers/_vmware-to-charmed-openstack.html
Added the new campaign takeover and engage page.
=> OpenStack WP campaign 

.circleci/config.yml, .github/workflows/linkchecker.yaml, Dockerfile, requirements.txt
- Update talisker v0.18.0
- Update docker image to focal
- Update to use gevent
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag charmed-osm.com  .`
-  `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key charmed-osm.com`
- http://0.0.0.0:8006/
- Play around with the site and make sure it works well
=> Update to focal

webapp/app.py
Updated the number of blog posts to display on list pages to 12
- http://0.0.0.0:8010/blog
- See that there are 12 items on this and following list pages
Fixes #392
=> Update blog list pages to include 12 items

templates/index.html
Updated the list of homepage takeovers
- ./run
- http://localhost:8010/
- Check that there are 3 takeovers in rotation
=> Update takeover list

Dockerfile, requirements.txt
Fix Python dependencies issue
- Pull the branch
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag test .`
- `docker run -ti -p "8010:80" --env SECRET_KEY=secret_key test`
=> Fix Python dependencies issue

.github/workflows/linkchecker.yaml
Added conditional to avoid scheduled cronjobs to run in our forks.
=> GitHub Action conditional for main repo

releases.yaml, requirements.txt, templates/about/index.html, templates/download/index.html, templates/download/thank-you/index.html, templates/index.html
- Add 20.04.1 download link for desktop and server 
- Update About page #424 
- Update Home page
=> 20.04.1 download link upate & pages update

releases.yaml
- Updated releases.yaml, but it isn't visible on the site... just code review
code review only 
Fixes #427
=> Update for 18.04.5 point release

templates/engage/ubuntu-tech-live-episode-1.html, templates/index.html, templates/takeovers/_iot-webinar_session_1.html
Webinar takeover and sign up page
Update takeovers list
Update index page
=> Webinar takeover and sign up page

requirements.txt, webapp/app.py
Updates blog to the latest version to fix a 500 error.
Go to https://cn.ubuntu.com/blog?page=3
You get 500
Go to https://cn-ubuntu-com-431.demos.haus/blog?page=3
It worx!
#https://github.com/canonical-web-and-design/canonicalwebteam.image-template/issues/47
=> Update blog version to 6.2.3

templates/engage/ubuntu-tech-live-episode-2.html, templates/engage/ubuntu-tech-live-episode-3.html, templates/index.html, templates/takeovers/_iot-webinar_session_3.html
- Taking down the case study takeover
- Add new webinar takeover & engage page
- Update index page of home page
=> Add new webinar page

templates/engage/redhat-openstack-comparison-whitepaper.html, templates/index.html, templates/takeovers/_redhat-openstack.html
- Add takeover and engage page for RH comparison WP 
- Update the index page
=> New RH WP campaign added

templates/about/index.html, templates/base_index.html, templates/cloud/index.html, templates/containers/index.html, templates/desktop/index.html, templates/download/index.html, templates/internet-of-things/index.html, templates/templates/base.html
Add meta description for the pages for SEO
=> Add meta description for pages

templates/engage/ubuntu-tech-live-episode-1.html, templates/engage/ubuntu-tech-live-episode-2.html, templates/engage/ubuntu-tech-live-episode-3.html, templates/index.html, templates/webinars/index.html
- Removing the date of webinar pages 
- Adding a new page for webinar collection 
- Updating home page content : case study/whitepaper, 20.04 laptop image, webinars page section
=> Added webinars page & update page content

templates/engage/ubuntu-tech-live-episode-4.html, templates/index.html, templates/takeovers/_iot-webinar_session_4.html, templates/templates/header.html, templates/webinars/index.html
1. Add takeover and engage page for Nov webinar
2. Update webinars page content
=> Add webinar in Nov

templates/contact/index.html, templates/server/index.html, templates/support/index.html, templates/templates/header.html
1. Add support page
2. Update the navigation tab
3. Add partner logo into server page
=> Add support page & update tabs & logos

templates/download/index.html
Updated the download link to https over http
Check the code.
Check the link works.
Fixes #469
=> Download via secure address

templates/support/index.html, templates/templates/base.html
- Add a new partner logo
- Add Baidu Tongji code
=> Few updates

templates/engage/ubuntu-tech-live-episode-5.html, templates/index.html, templates/support/index.html, templates/takeovers/_iot-webinar_session_5.html, templates/templates/header.html
1.  Pages update
- /templates/index.html
- /templates/header.html
- /support/index.html
2. New takeover and engage page for incoming webinar
- /takeovers/_iot-webinar_session_5.html
- /engage/ubuntu-tech-live-episode-5.html
=> Add webinar campaign & pages update

templates/engage/base_engage.html, templates/engage/shared/_engage_form.html
Fix form cta and add default
- Go to https://cn-ubuntu-com-485.demos.haus/engage and click on the `Ubuntu Tech Live` engage page
- Check that the form cta is correct
- You can compare it the current live one https://cn.ubuntu.com/engage/ubuntu-tech-live-episode-5
Fixes #484
=> Fix form cta and add default

.github/workflows/linkchecker.yaml
Revert the OS version used for the linkchecker action
=> Revert linkchecker to 18.04

package.json, webpack.config.js, yarn.lock
Remove Tenser dependency
- Check the demo looks the same as live
- Check the main.js is minified still
=> Remove Tenser dependency

.github/workflows/linkchecker.yaml
Make linkchecker ignore blog as it would need VPN access locally
Check code
=> Make linkchecker ignore blog

templates/cloud/index.html
Replace the conjure up tutorial with the microk8s one.
Check the new link works.
=> Fix tutorial 404 link

releases.yaml, templates/download/index.html
- Updated the release.yaml to 21.04
- Updated the download page to use the new release.yaml release notes
- look at /download and see that it is ready for 21.04
- 
Fixes #515
=> WIP: Initial update for 21.04

templates/contact/index.html, templates/internet-of-things/features/full-disk-encryption.html, templates/internet-of-things/features/index.html, templates/internet-of-things/features/ota-updates.html, templates/internet-of-things/features/recovery.html, templates/internet-of-things/features/secondary-nav.html, templates/internet-of-things/features/secure-boot.html, templates/internet-of-things/index.html, templates/internet-of-things/secondary-nav.html
1. Added and translated features pages of Ubuntu Core from [](https://ubuntu.com/core/features) including:
- Features
- Secure boot
- Full disk encryption
- Recovery
- OTA updates
2. Creating a submenu for features pages.
3. Updated snap store screenshot of the internet-of-things page.
4. Updated Contact page text.
=> Added UC features pages & updated page's content

static/sass/styles.scss, templates/cloud/index.html, templates/cloud/public-cloud.html, templates/cloud/secondary-nav.html, templates/shared/_ubuntu_pro_on_public_cloud.html
- Fix server page text alignment issue
- Update the cloud page because the logos list broken and the content is out of date
- Created subpage for public cloud 
Fix #539
=> Fix align issue and update cloud page

templates/download/cloud.html, templates/download/desktop.html, templates/download/server/arm.html, templates/download/server/choose.html, templates/download/server/provisioning.html, templates/download/server/step1.html, templates/download/server/step2.html
- Updated download sub-pages titles
- Fix the HTTP of links with HTTPS
=> Update page titles and fix http issues

templates/support/index.html
Add a UA introduction doc in the support page.
=> Add UA intro document

templates/blog/index.html
Update the pagination mark up to match the new Vanilla classes.
- Open the demo
- Go to /blog
- Scroll to the bottom and see the pagination looks right
- Use the pagination and check its working as expected
=> Update the blog pagination pattern

templates/404.html
- Updated CSS classes
- Translated the texts in Chinese (Double checked with Zihe) 
View page at: https://cn-ubuntu-com-559.demos.haus/404
Fixes #499
=> Update 404 page

templates/support/esm.html, templates/support/index.html
- Update /support/esm page support date info and content.
- Update /support page content.
=> Update ESM coverage info and pages content

templates/enterprise/index.html, templates/enterprise/secondary-nav.html, templates/shared/_release_schedule.html, templates/templates/header.html
- Create a new overview page for products and services(/enterprise)
- Update the menu order(rename tab title and re-order) 
- Page content update
=> Add a new page and content update

static/js/src/form-validation.js, templates/blog/newsletter-form.html, templates/contact/index.html, templates/download/server/thank-you.html, templates/engage/2004-launch.html, templates/engage/shared/_engage_form.html
- Post forms to `https://ubuntu.com/marketo/submit`
- Decapitalise input names 
- Update hidden inputs
1. Go to https://cn-ubuntu-com-594.demos.haus/contact
2. Fill in the form and submit it 
3. Check it's submitted and redirect to a thank you page on cn.unbuntu.com 
4. Check the submitted data is on the list in marketo 
Fixes [#4734](https://github.com/canonical-web-and-design/web-squad/issues/4734)
=> Update marketo endpoint

templates/blog/newsletter-form.html
Update canonicalUpdatesOptIn input value to "yes"
1. Go to https://cn-ubuntu-com-604.demos.haus/blog
2. Fill in the form and submit it
3. Check the form is submitted
4. Check the submitted data is on the list in marketo (form ID is 3647)
#603
=> Fix Marketo form 3647 failed to submit

releases.yaml
Updates checksums for 22.04 release
=> Update checksums for 22.04

templates/shared/pricing/_ua-for-infrastructure.html
- Updated table copy as requested [here](https://github.com/canonical-web-and-design/web-squad/issues/5116)
- Visit https://cn-ubuntu-com-618.demos.haus/cloud/openstack
- See that the table has been updated
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5116
=> Update ua-for-infra table copy

releases.yaml, static/sass/styles.scss, templates/desktop/developers.html, templates/desktop/features.html, templates/desktop/index.html, templates/desktop/organisations.html, templates/desktop/partners.html, templates/download/desktop.html, templates/download/index.html, templates/download/raspberry-pi.html, templates/download/server/step1.html, templates/download/server/thank-you.html, templates/download/xilinx.html, templates/server/index.html, templates/shared/_desktop_contextual.html, templates/shared/contextual_footers/_download_desktop_installation.html
Changes are made from the PR of EN website https://github.com/canonical-web-and-design/ubuntu.com/pull/11501
The checksums in the YAML file are not used, so no need to update them.
=> 22.04 refresh & updates

templates/desktop/index.html, templates/desktop/organisations.html, templates/desktop/secondary-nav.html, templates/download/raspberry-pi.html, templates/support/advantage.html, templates/support/index.html, templates/support/secondary-nav.html
- Refresh /desktop/organisation page 
- Update the support page and add the advantage page
=> Organisation page refresh and update 

static/sass/_pattern_gaming.scss, templates/desktop/developers.html, templates/desktop/features.html, templates/desktop/index.html, templates/desktop/organisations.html, templates/desktop/partners.html, templates/desktop/secondary-nav.html, templates/shared/_education-discount.html, templates/support/esm.html, templates/support/index.html, templates/support/secondary-nav.html
- Update the images for Desktop pages
- Update the Support pages
=> Desktop pages update

templates/index.html
Removed the Netflix logos from the homepage
- Check there is no Netflix on the homepage
- Check the logo sections look ok
Fixes https://github.com/canonical/web-squad/issues/6010
=> Remove Netflix from the site

static/sass/styles.scss, templates/cloud/openstack/index.html, templates/desktop/organisations.html, templates/enterprise/index.html, templates/enterprise/secondary-nav.html, templates/pricing/index.html, templates/pricing/pro.html, templates/pricing/secondary-nav.html, templates/shared/_call-sales.html, templates/shared/_security-patching-logo-cloud.html, templates/shared/pricing/_maas-pricing.html, templates/shared/pricing/_openstack-kubernetes-lma.html, templates/shared/pricing/_ua-advanced-storage.html, templates/shared/pricing/_ua-for-infrastructure.html, templates/support/index.html, templates/support/pro.html, templates/support/secondary-nav.html
- Create the Pro, Pricing page from ubuntu.com
- Update /support, /desktop/organisations, /cloud/openstack, /enterprise pages content.
=> Add Pro and related pages

templates/landscape/features.html, templates/landscape/index.html, templates/landscape/install.html, templates/landscape/pricing.html, templates/landscape/secondary-nav.html, templates/shared/pricing/_ua-for-infrastructure.html, templates/support/index.html, templates/support/pro.html, templates/support/secondary-nav.html
- Add Landscape pages from ubuntu.com
- Update support & pro page
- Update the links
=> Add landscape page

.github/workflows/pr.yaml, templates/shared/_education-discount.html, templates/support/index.html
- Add partner logos on the support page.
=> Add partner logos

templates/download/iot/intel-iotg.html, templates/internet-of-things/core/features/index.html, templates/internet-of-things/secondary-nav.html
- Fix the core/features missing links
- Update the download/intel IoT page content
FIxes https://github.com/canonical/cn.ubuntu.com/issues/664#issuecomment-1370720270
=> Fix missing links & update Intel IoT page

templates/templates/header.html
Add navigation tracking events to the header navigation
- Check the event values match the link values
- If you have GA plugin check the events trigger on the demo when navigating around
=> WD-2811 Add navigation tracking events

package.json, templates/desktop/developers.html, templates/desktop/index.html, templates/desktop/organisations.html, templates/desktop/secondary-nav.html, templates/index.html, templates/shared/_pro_strip.html, templates/shared/_security-patching-logo-cloud.html, templates/support/index.html, yarn.lock
- Add 18.04 EOL notice
- Update desktop pages
- Update the support page
=> Add 18.04 EOL & page update

releases.yaml
Replace 22.04.2 with 22.04.3
1. Open the demo
2. Check the download work
=> Replace 22.04.2 with 22.04.3

.github/workflows/pr.yaml, .webpack/entry.js, package.json, static/js/src/cookie-policy.js, static/sass/styles.scss, templates/templates/base.html, yarn.lock
- Updated the coookie policy to v3.6.3
- View the demo in an incognito web browser
- **Before** accepting cookies, 
- Open developer tools and in the console type in `dataLayer`
- There should be a `{"consent", "default"}` object in the dataLayer
- **After** accepting cookies, 
- There should be a `{"consent", "update"}` object in the dataLayer
=> Update cookie policy to v3.6.3

releases.yaml, templates/download/desktop.html, templates/download/index.html, templates/download/server/step1.html, templates/index.html
-  Update 24.04 download links
- Fix a translation
=> Update 24.04 release links

.github/workflows/pr.yaml, templates/download/desktop.html
Most 24.04 updates were reviewed and updated in https://github.com/canonical/cn.ubuntu.com/pull/720, these are just some additional updates according to copy doc.
Check https://cn-ubuntu-com-722.demos.haus/download/desktop against [copy doc comment](https://docs.google.com/document/d/1-rYu9BV4mN04yXn01QhBillOyHQOeuCbuGKiJQpJjYs/edit#heading=h.lf91i2rsa8g8)
Fixes https://warthogs.atlassian.net/browse/WD-11402
=> 24.04 copy update

.djlintrc, .github/workflows/pr.yaml, requirements.txt
- Config for djlint
- Reference taken from https://github.com/canonical/ubuntu.com/blob/main/.djlintrc#L7
[List of steps to QA the new features or prove the bug has been resolved]
[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]
=> Added config for djlint (.djlintrc)

.djlintrc, .github/workflows/pr.yaml, .webpack/entry.js, requirements.txt, static/js/src/tabbedContent.js, static/sass/_pattern_tabs.scss, templates/download/risc-v/index.html, templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-4.html, templates/download/risc-v/tab-5.html, templates/download/risc-v/tab-6.html, templates/download/risc-v/tab-7.html
Webpage refresh for the page /download/risc-v
- Check out this feature branch
- Run the site using the command dotrun
- View the site locally in your web browser at: http://0.0.0.0:8010/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [Copydoc](https://docs.google.com/document/d/1SPeefGBJBh99XWEx0newZHPxp56mZuaElq1YtUzfY4M/edit)
- [Demo](https://cn-ubuntu-com-725.demos.haus/download/risc-v)
[WD-11512](https://warthogs.atlassian.net/browse/WD-11512)
[WD-11512]: https://warthogs.atlassian.net/browse/WD-11512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-11512 Refresh /download/risc-v page

releases.yaml, templates/download/desktop.html
Update the `releases.yaml` to match the one on ubuntu.com.
Open the demo download a few versions and check they work.
=> fix(releases): Update the releases to 24.04.1

releases.yaml, templates/download/desktop.html, templates/download/server/step1.html
Update the `releases.yaml`
Changed some hardcoded versions to be dynamic.
Updated the image used for the latest version
1. Open the demo
2. Go to the download page
3. Download the desktop
4. Check the release notes work
5. Download server
=> Update the release with 24.10

.github/workflows/live-links.yml, .github/workflows/pr.yaml
Added a link checker that will check daily if there are any broken links in the project and report it to MM channel (similarly to how it works for ubuntu.com).
=> add link checker GH action

templates/microcloud/index.html
Add new page at `/microcloud`
Make sure page's design matches figma design
- [Design](https://www.figma.com/design/ehBGHH1plhbzGaWGZBnyLG/cn.ubuntu.com?node-id=86-2872&t=tvd3rI8eYydtDfHL-0)
- [Copydoc](https://docs.google.com/document/d/1BIMPWssA-gxRp6N_ViEfGGdjXGLZepXMPau24BvYS7E/edit?tab=t.0)
- [Demo](https://cn-ubuntu-com-749.demos.haus/microcloud)
[WD-20398](https://warthogs.atlassian.net/browse/WD-20398)
[WD-20398]: https://warthogs.atlassian.net/browse/WD-20398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-20398 Dev - Create [cn.ubuntu.com/microcloud]

.github/workflows/live-links.yml, templates/index.html
- Fix failing links on homepage
- Fly-by work: Update live-links.yaml to exclude more error codes 
- Go to demo homepage
- Check that the updated links work and don't return 404
Fixes [WD-21942](https://warthogs.atlassian.net/browse/WD-21942)
[WD-21942]: https://warthogs.atlassian.net/browse/WD-21942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Failing links on homepage

.github/workflows/live-links.yml
- Ignore 401 errors on linkchecker
[List of steps to QA the new features or prove the bug has been resolved]
[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]
=> chore: Ignore 401 error on linkchecker

.github/workflows/linkchecker.yaml
fix: Use an updated flow for linkchecker
Check the code matches that for [ubuntu.com](https://github.com/canonical/ubuntu.com/blob/main/.github/workflows/live-links.yaml)
https://warthogs.atlassian.net/browse/WD-22092
=> fix: Use an updated flow for linkchecker

.github/workflows/live-links.yml, templates/blog/newsletter-form.html, templates/cloud/openstack/index.html, templates/internet-of-things/smart-displays.html, templates/kubernetes/index.html, templates/shared/_release_schedule.html
Fix broken links flagged by [link checker](https://github.com/canonical/cn.ubuntu.com/actions/runs/16018837789)
- Install linkchecker
`pipx install linkchecker`
- Check out this branch
- Run the project
- Run linkchecker from within the project
`linkchecker --no-warning http://0.0.0.0:8010`
- *anything under /blog, will always fail*
https://warthogs.atlassian.net/browse/WD-23443
=> Fix broken links

templates/contact/index.html
- Update the QR code for the new contact.
=> Update wechat QR code

templates/about/index.html
- Replaced `http` with `https` for failing links
- Verify the affected links are working as expected.
=> Fix failing links
