canonical/cn.ubuntu.com

- templates/phone/index.html
* removed buy links and button on the /phone page like we have on ubuntu.com
1. go to /phone
2. see no buy links or buttons like in the [copy doc](https://docs.google.com/document/d/1wrS0ojZ4B_2UdbxDyIzr-iZPA_ti-JCxtO9QXfoKdUw/edit)
Fixes #114
> remove buy links from /phone

- templates/news/index.html
- Removed the last link on the `/news` page
- Corrected the spelling of Youku
Check `/news` in browser and see that the changes above have been made.
Fixes #117
> remove link to out-of-date video and correct the name of Youku

- templates/download/index.html
Updated the download links to the desktop LTS to the new point release.
- Run `make clean-all run`
- Go to http://127.0.0.1:8010/download/
- Check that the two links work unlike on live
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/121
Fixes https://github.com/canonical-websites/cn.ubuntu.com/pull/122
> Update the download link to 16.04.2

- static/css/_scratch.scss
Moved the hover background styling to a medium breakpoint from large only.
- Pull branch
- Run `make clean-all run`
- Go to http://localhost:8010/ on medium screen
- Hover over the nav and see that it light orange not grey
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/55
> Fix navigation styling on medium screens

- templates/download/index.html
Removed the `no-margin-bottom` to the download sections. Also moved the column styling on to the box so the boxes take up the entire space even if the content is short.
- Pull branch
- Run `make run`
- Go to http://localhost:8010/download on small screen
- Check the download boxes work better then on live http://cn.ubuntu.com/download/
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/60
> Add margins to all download sections

- templates/download/index.html
Fixed the URLs on the download page
- `./run`
- go to [/download/](http://localhost:8010/download/)
- See that the upper two buttons correctly download ISOs (compare to 404s on live)
Fixes #144
> Fix URLs to latest ISO version

- manage.py
Python 3 currently causes problems in our deployment set up while we are migrating services over.
> Change manage.py to stop pointing at python 3

- .editorconfig
- package.json
- templates/contact/index.html
- templates/desktop/index.html
- templates/templates/footer.html
- yarn.lock
**Note**: This branch is built on the changes in https://github.com/canonical-websites/cn.ubuntu.com/pull/150 - that PR should be landed before this one.
- Bump VF to 1.5.1
- Update /desktop markup to match Vanilla styles
- Pull code
- Sanity check file deletions
- View desktop page on http://0.0.0.0:8010/desktop
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/67
> Convert /desktop to Vanilla v1 styles

- templates/server/index.html
- Converted /server section of the site to Vanilla v1 styles
- Pull code
- Sanity check file deletions
- View desktop page on http://0.0.0.0:8010/server
- Click through to page and ensure layout looks correct
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/71
> Upgrade v1 markup for /server

- templates/contact/index.html
- Converted /contact section of the site to Vanilla v1 styles
- Pull code
- Sanity check file deletions
- View desktop page on http://0.0.0.0:8010/contact
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/66
> Upgrade markup on /contact to v1 styles

- templates/cloud/index.html
Convert cloud page to Vanilla
- Pull code
- Sanity check file deletions
- View desktop page on http://0.0.0.0:8010/cloud
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/65
> Convert cloud page to Vanilla

- templates/news/juju-top-twelve.html
Fix up /news/juju-top-twelve/ for v1 as it was missed on the /news sweep.
- Pull code
- Run ./run serve --watch
- View http://0.0.0.0:8010//news/juju-top-twelve/ and check it looks correct
> Fix up /news/juju-top-twelve/ for v1

- templates/download/index.html
Update download links for 16.4 LTS
- Clone repo
- Checkout branch
- `./run serve`
- Go to [downloads page](http://0.0.0.0:8010/download/)
- Check that download links for 16.4 LTS download version 16.4.4
[Fixes #187](https://app.zenhub.com/workspace/o/canonical-websites/cn.ubuntu.com/issues/187)
> Update download links

- templates/download/index.html
- templates/internet-of-things/index.html
- templates/templates/base.html
Update the IoT image and removed some relative links to make the site secure again.
- Go to /iot
- See that the store image matches https://snapcraft.io/store
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/211
> Update the iot store image

- Dockerfile
- entrypoint
- package.json
- requirements.txt
Fixes https://github.com/ubuntudesign/base-squad/issues/103
QA
--
``` bash
./run
```
See that it mentions "Booting worker" 3 times. Go to http://localhost:8010, see the site! Then:
``` bash
docker build --tag cn --build-arg COMMIT_ID=`git rev-parse HEAD` .
docker run -ti -p 8099:80 cn
```
See that it mentions "Booting worker" 3 times. Go to http://localhost:8099, see the site again!
Also, check the `X-VCS-Revision` shows correctly:
``` bash
$ curl -Is localhost:8099 | grep VCS
X-VCS-Revision: {commit_hash}
```
> Entrypoint for talisker gevent workers

- .circleci/config.yml
- .travis.yml
- package.json
- templates/templates/footer.html
Add CircleCI workflow to the project. Steps added are:
- Python tests.
- Python lint
- Sass lint
Check the CI wokrflow under my CircleCI space.
OR
- Fork cn.ubuntu.com.
- Add this feature branch to your fork.
- Enable project in your own CircleCI space.
- Follow the steps in https://circleci.com/docs/2.0/examples/#section=configuration to trigger a build.
- Check the workflow ran properly.
Fixes https://github.com/ubuntudesign/base-squad/issues/210
> Add CircleCI workflow

- templates/desktop/index.html
Updated the list of snaps on the desktop overview page to match top snaps, and removed deprecated snaps leading to 404's. 
- Check that the Snaps go to the right URL's
Fixes #236
> Updated snaps in desktop overview

- package.json
- yarn.lock
- Updated version of site to Vanilla 1.8
1. Check out this feature branch
2. Run the site using the command `./run`
3. View the site locally in your web browser at: [http://0.0.0.0:8010/](http://0.0.0.0:8010/)
4. Compare with [live](https://cn.ubuntu.com/) and ensure that the site looks the same
> Update to Vanilla v1.8

- templates/templates/footer.html
Link in footer was leading to 404. Fix the link, and change link text to something friendlier (same as www.ubuntu.com).
QA
--
`./run`, go to footer, see the glorious link to "Legal information".
> Fix legal footer link

- static/sass/styles.scss
This was leading to this error:
$ node-sass --include-path node_modules static/sass --output static/css && postcss --use autoprefixer --replace 'static/css/**/*.css' && postcss --use cssnano --dir static/minified 'static/css/**/*.css'
{
"status": 1,
"file": "/home/robin/git/cn.ubuntu.com/static/sass/styles.scss",
"line": 12,
"column": 1,
"message": "File to import not found or unreadable: ../global-nav/src/sass/main.",
"formatted": "Error: File to import not found or unreadable: ../global-nav/src/sass/main.\n        on line 12 of static/sass/styles.scss\n>> @import '../global-nav/src/sass/main';\n\n   ^\n"
}
QA
--
Check `./run build` now passes, and `./run` runs the site.
> Fix bad merge

- .dockerignore
- redirects.yaml
- requirements.txt
- webapp/settings.py
- webapp/urls.py
The main thing here is that redirects work. Most importantly, redirects to remove slashes. Also, ignore node_modules from docker image.
QA
--
`./run`
Now make sure the site works, browse around. Also check:
``` bash
$ curl -I http://localhost:8010/internet-of-things/
HTTP/1.1 302 Found
Location: /internet-of-things
$ curl -I http://localhost:8010/internet-of-things
HTTP/1.1 200 OK
```
> Fix navigation with redirects

- .circleci/config.yml
To check the site builds and runs fine, returning a <400 status.
Similar to developer.ubuntu.com and blog.ubuntu.com.
QA
--
See the "test-site" test pass.
> Add "test-site" CI step

- static/sass/styles.scss
Fixes https://github.com/canonical-websites/cn.ubuntu.com/issues/277
QA
--
`./run`, see that the Canonical logo in global nav is indented to align with the "Ubuntu" logo, like on www.ubuntu.com
> Indent Canonical logo in global nav

- package.json
- requirements.txt
- static/sass/_settings_colors.scss
- static/sass/styles.scss
- templates/cloud/index.html
- templates/containers/index.html
- templates/index.html
- templates/internet-of-things/index.html
- templates/server/index.html
- webapp/settings.py
- yarn.lock
- Updated the /server page per docs provided in the [brief](https://docs.google.com/document/d/1onVw-6_3zNzGXSyny8L8unC90QdVH-DJ5ZPEwdm0iNw/edit)
- Added the {{ ASSET_SERVER_URL }} pointing to cloudinary and added this to non svg, pdf and js files
- Update the version of Django and global_nav
1. download this branch
2. ./run the site 
3. review the [server page](http://0.0.0.0:8010/server)
4. compare to the doc in the brief
Fixes #290
> Update to server page, cloudinary, asset_serve_url

- templates/templates/header.html
Fixes https://github.com/ubuntudesign/base-squad/issues/439
- Includes the blog route into the navbar
##
- `./run`
- make sure that the last item in the navbar links to the blog
- make sure that when you are on the blog page, the navigation item is highlighted
> Includes the blog into the navbar

- static/sass/_settings_colors.scss
- Change the active navigation link color setting
- check out the demo service link
- make sure that the route you are at is highlighted in the nav with an orange underlin
> Sets the active navigation link color to orange

- templates/templates/header.html
- Checks if the beginning of a path contains `/blog` and highlights that blog item accordignly
-  on the demo service, navigate to a blog article and verify that the navigation item is still highlighted
> Checks for blog as path root in blog item

- requirements.txt
- templates/blog/blog-card.html
- Correctly access the article object in template to display the category in the footer
- ./run
- go to `localhost:8010/blog` and make sure that some articles correctly display a category name in the footer
> Correctly access the display category for the footer

- .gitignore
- webapp/urls.py
Use `re_path` for urls defined as regex in `urls.py` 
https://docs.djangoproject.com/en/2.2/ref/urls/#re-path
Add .webcache to gitginore in the same PR
- `./run`
- http://127.0.0.1:8010/engage/robot-operating-system-choice-cn
- Page should be accessible
- Navigate in the site and make sure other templates work
Fixes https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/313
> Use re path 

- requirements.txt
- Update blog module to 1.3.5 to include https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/32
- `./run`
- go to `hhttp://localhost:8010/blog/canonical-at-open-infrastructure-summit-denver` and make sure it displays (is english content, and not chinese)
> Updates blog module to 1.3.5 to fix 404 on article pages

- static/js/global-nav.js
Set the max-width of the global-nav
- Load the demo
- Check the Canonical logo in the global nav aligns with the Ubuntu logo below.
Fixes https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/331
> Set the max-width of the global-nav

- templates/blog/article.html
- templates/engage/robot-operating-system-choice-cn.html
- templates/templates/_extra_metadata.html
- templates/templates/base.html
- webapp/settings.py
- webapp/templatetags/utils.py
- Add extend_with_args to the cn.u.c site for blog posts, engage, etc...
- Download this PR
- ./run the site
- Look at head of and [engage page](http://0.0.0.0:8010/engage/robot-operating-system-choice-cn) and a [blog post](http://0.0.0.0:8010/blog/ubuntu-5g-bt) and see they have the twitter/opengraph info
Fixes #333
> Add social metadata to site

- templates/engage/developer-desktop.html
- templates/engage/thank_you_dd.html
- templates/index.html
- templates/takeovers/_active-directory-takeover.html
- templates/takeovers/_desktop-developer-takeover.html
Merge the takeovers js code from jp.ubuntu.com for multi-takeovers. (now 2 takeovers)
Change the main page code and load takeover template. 
Create the new engage page for Desktop dev whitepaper campaign.
> multi-takeover & Desktop WP

- requirements.txt
Bump blog to v5.0.0
This removes all the django bits.
Fixes #373 
- `./run`
- `/blog` Make sure that blog still works as usual.
> Bump blog to v5.0.0

- templates/about/index.html
Corrected link to canonical.com
1. Launch the site
1. Go to /about
1. Find the link to “Canonical” and follow it
1. Observe that you’re now on canonical.com
#377
> Corrects link to canonical.com

- .github/workflows/linkchecker.yaml
- templates/cloud/index.html
Run the linkchecker nigthly to make sure we are not pointing to 404s from the site.
This job will do a `deep` search as it checks also every external links.
I think the next step would be to have a endpoint where we could send the report.
> Linkchecker nigthly

- templates/about/index.html
Removed a list item that referred to the old Mythbuntu flavor from the /about page.
Confirm Mythbuntu is no longer mentioned anywhere
N/A
> Remove reference to discontinued Mythbuntu from /about

- releases.yaml
- templates/download/index.html
- templates/templates/base.html
- Updated the releases.yaml
- Added logic to hide latest releases the are less than LTSs
- Fixed up the IoT core image downloads to be inline with ubuntu.com
- Added meta_copydoc to page and base
- download this branch
- go to http://0.0.0.0:8010/download
- see that it only shows 20.04
Fixes #388
> Initial update of the /download page for focal

- releases.yaml
- templates/download/index.html
- Fixed bad server link
- Updated releases.yaml (however not used for checksums currently)
- https://0.0.0.0:8010/download and see that the download buttons work
> Update release info

- templates/index.html
- templates/takeovers/_2004-takeover.html
#327  Done
- Added release takeover as a non-JS takeover
- Removed all JS takeovers from the list
- Updated the JS to not error when there are no takeovers
- http://0.0.0.0:8010
- See that there is a takeover (with your browser in any language)
Fixes #397
> Takeover fix

- templates/about/index.html
* Updated the Lubuntu link to a non-deprecated site, and swapped the reference to LXDE to LXQt. Removed the creepy Google Analytics tracker.
* Removed the Ubuntu GNOME link. That flavor died when Canonical stopped developing the Unity DE and changed the default Ubuntu environment to Gnome Shell, years ago.
Check rendering of the /about page.
N/A
> /about: Update Lubuntu, remove Ubuntu GNOME

- templates/contact/index.html
- templates/engage/openstack-ussuri-webinar.html
- templates/index.html
- templates/takeovers/_openstack-ussuri.html
- Create takeover and engage page for OpenStack Ussuri webinar
- Update index page, remove 20.04 takeover from cycle list 
- Update contact page, remove phone number
> New OpenStack campaign & contact page update

- requirements.txt
- templates/blog/blog-card.html
- webapp/app.py
This will do two things:
1) Rewrite the admin.insights.ubuntu.com/wp-content to ubuntu.com/wp-content
2) Enable cloudinary for both thumbnails and article images
Click on the demo link. Browse to `/blog`.
Check that thumbnails are ok. Click on some articles, check the images are fine:
The urls of the images should be pointing to `ubuntu.com/wp-content` not `admin.insights.ubuntu.com/wp-content`
The cloudinary service should be enabled for both thumbnails and article images.
> Update blog module version

- .webpack/entry.js
- package.json
- static/js/src/cookie-policy.js
- static/sass/styles.scss
- templates/templates/base.html
- templates/templates/footer.html
- yarn.lock
Add cookie-policy v3.0.3
**Do not merge until @pmahnke has done the GTM changes**
- Load the demo and you should see the cookie policy
- Open the manager and select something
- See it is gone
- Click the link in the footer to manage cookies
- See it opens again without errors in the console.
Fixes https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/440
> Add cookie-policy v3.0.3

- releases.yaml
- templates/download/index.html
Update the releases.yaml for 20.10 release
- Open the demo
- Go to /download
- See that there is a 20.10 download option
Fixes https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/450
> Update the releases.yaml for 20.10 release

- templates/engage/2004-launch.html
- templates/engage/developer-desktop.html
- templates/engage/microsoft-active-directory.html
- templates/engage/openstack-ussuri-webinar.html
- templates/engage/redhat-openstack-comparison-whitepaper.html
- templates/engage/robot-operating-system-choice-cn.html
- templates/engage/shared/_base_engage_markdown.html
- templates/engage/ubuntu-tech-live-episode-1.html
- templates/engage/ubuntu-tech-live-episode-2.html
- templates/engage/ubuntu-tech-live-episode-3.html
- templates/engage/ubuntu-tech-live-episode-4.html
- templates/engage/uc18wb.html
- templates/engage/vmware-to-openstack.html
- templates/engage/xdf-maas-ebook.html
- fix border bleed [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3424) by adding `border-color:#cdcdcd;` to the fieldsets
1. Download this branch and run it.
2. compare http://0.0.0.0:8010/engage/ubuntu-tech-live-episode-3 with https://cn.ubuntu.com/engage/ubuntu-tech-live-episode-3
[live]
[this branch]
> Fix border bleed on fieldsets

- templates/engage/shared/_engage_form.html
Fix root URLs for engage thank-you pages
Can you only be done in production.
Fill up the form and it should redirect to the correct thank-you page
#520
> Fix root url for thank-you pages

- templates/internet-of-things/index.html
- templates/internet-of-things/secondary-nav.html
- Fix /internet-of-things submenu
- Removed extra `</a>`
- go to http://0.0.0.0:8005/internet-of-things and see that the subnav looks correct.
> Fix /internet-of-things submenu

- static/sass/_patterns_navigation.scss
- static/sass/styles.scss
- templates/support/esm.html
- Fix secondary navigation
- Remove old styles fixed by Vanilla 2.30
- Fix background color on ESM support page
- Compare currente site navigation (when in the IoT page) https://cn.ubuntu.com/internet-of-things
with https://cn-ubuntu-com-537.demos.haus/internet-of-things
- Fixed background color on https://cn-ubuntu-com-537.demos.haus/support/esm
Fixes #536
> Fix secondary nav after Vanilla 2.30 update

- templates/support/index.html
Fix broken logos on /support
- Check /support logos is not broken anymore (compare with https://cn.staging.ubuntu.com/support)
> Vanilla v3 fixes

- templates/blog/index.html
- templates/blog/newsletter-form.html
- templates/server/secondary-nav.html
- Ａdd a sub-tab for security notices
- Update blog subscription text because no more than 1 options are available 
- Fix the navigation icon for previous and next page display issues since the "p-icon--contextual-menu" is replaced with "p-icon--chevron-down" in [Vanilla V3](https://vanillaframework.io/docs/migration-guide-to-v3)
> Fix the blog navi icon

- releases.yaml
- Bump the point release from 20.04.3 to 20.04.4
- Check the file names and checksums match the ones in [the issue](https://github.com/canonical-web-and-design/web-squad/issues/4841#issuecomment-1049688375).
- Visit:
- https://cn-ubuntu-com-607.demos.haus/download/desktop
- https://cn-ubuntu-com-607.demos.haus/download/server/step1
- https://cn-ubuntu-com-607.demos.haus/download/raspberry-pi (scroll down to "Download Ubuntu Server")
- See that any links to download point to the links given in the issue
- **Note:** The download **won't** work yet
- Go to https://cn-ubuntu-com-607.demos.haus/download/alternative-downloads and see it says 20.04.4, not 20.04.3
Fixes [#4841](https://github.com/canonical-web-and-design/web-squad/issues/4841)
> Bump the point release to 20.0.4.4

- requirements.txt
This appears to have been added in 3ebc269d9326980bf9a3d281fbdf6f2dd7320cf7,
even though I don't think it was used even then.
QA
--
`dotrun clean`, then `dotrun` run the site, check it works.
> Remove unused canonicalwebteam.search module

- konf/site.yaml
Some discourse API features namely the discourse plugin data-explorer that will be used in [new engage pages]() and blocking google search from [indexing discourse posts](https://github.com/canonical-web-and-design/web-squad/issues/5661) require discourse API keys.
No QA really, once we merge this, we can change the permissions so that engage pages are not accessible without login, but this can only happen after merge.
Just check that `/engage` works and check the individual engage pages work
Partially https://github.com/canonical-web-and-design/web-squad/issues/5661
Partially https://github.com/canonical-web-and-design/ubuntu.com/issues/11503
> Add discourse API key

- releases.yaml
- updated releases.yaml with the checksums for 22.04.1
- Check out this feature branch
- Run the site using the command ./run serve or dotrun
- View the site locally in your web browser at:
- http://0.0.0.0:8010/download/alternative-downloads
- http://0.0.0.0:8010/download/desktop
- http://0.0.0.0:8010/download/server/step1
- http://0.0.0.0:8010/download/raspberry-pi
- See that they all point to 22.04.1
- The checksums should match the ones provided by Lukasz:
```
c396e956a9f52c418397867d1ea5c0cf1a99a49dcf648b086d2fb762330cc88d *ubuntu-22.04.1-desktop-amd64.iso
10f19c5b2b8d6db711582e0e27f5116296c34fe4b313ba45f9b201a5007056cb *ubuntu-22.04.1-live-server-amd64.iso
680c2c1770b53d90e825fd9a40178f605af47acfff681ad5f68d38094d1c32eb *ubuntu-22.04.1-preinstalled-desktop-arm64+raspi.img.xz …
```
> update releases.yaml for 22.04.1

- releases.yaml
- templates/download/index.html
- templates/download/raspberry-pi.html
- templates/download/server/step1.html
- updated list of checksums and releases.yaml latest
- updated mascot on /download
- updated mascot /download/server
- added 22.10 section to /download/raspberry-pi to match what's going live on ubuntu.com for the release (a 22.10 desktop download cta that sits alongside the LTS listing)
- Visit https://cn-ubuntu-com-649.demos.haus/download
- See that the mascot is correct
- Visit https://cn-ubuntu-com-649.demos.haus/download/desktop
- See that 22.10 is listed with links to download it (the links won't work yet)
- Visit https://cn-ubuntu-com-649.demos.haus/download/server/step1
- See that the mascot is correct and that 22.10 is listed with links to download it (the links won't work yet)
- Visit  https://cn-ubuntu-com-649.demos.haus/download/raspberry-pi
- See that 22.10 is listed with …
> update for 22.10 release

- templates/takeovers/index.html
Fix image in ubuntu takeovers
Go to https://cn-ubuntu-com-657.demos.haus/takeovers all images are showing now (in contrast https://cn.ubuntu.com/takeovers is not showing images)
Fixes https://github.com/canonical/cn.ubuntu.com/issues/656
> Fix takeover image

- releases.yaml
- templates/download/risc-v/index.html
- templates/download/risc-v/tab-1.html
- templates/download/risc-v/tab-2.html
- templates/download/risc-v/tab-3.html
- templates/download/risc-v/tab-4.html
- Update releases.yaml file to include the new 22.04.2 release.
- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8010/
- Check that there are no mentions of 22.04.1
> Update releases.yaml to add 22.04.2

- templates/index.html
- Adds ga tracking for takeover impressions
- Load the homepage (make sure a takeover loads) and check the ga event has been pushed with the appropriate data
Two ways to do this:
1. run the branch locally follow the guide in the [google analytic docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) to see tga events in the network tab
2. (Recommended) Download a broswer extension that tracks GA events, I am using [tag legacy](https://chrome.google.com/webstore/detail/tag-assistant-legacy-by-g/kejbdjndbnbjgmefkgdddjlbokphdefk)
Should look something like: 
```
{
"gtm.start" : 1678275907959 ,
"event" : "gtm.js" ,
"gtm.uniqueEventId" : 1
},
{
"event" : "gtm.dom" ,
"gtm.uniqueEventId" : 2
},
{
"event" : "NonInteractiveGAEvent" ,
"eventCategory" : …
```
> Add ga tracking for takeover impressions

- templates/blog/newsletter-form.html
- templates/contact/index.html
- templates/download/server/thank-you.html
- templates/engage/2004-launch.html
- templates/engage/shared/_engage_form.html
Add acquisition URLs for marketo to obtain the full path.
- Go to https://cn-ubuntu-com-703.demos.haus/blog/canonical-ubuntu-core-22-is-now-available-optimised-for-iot-and-embedded-devices-cn
- Submit the newsletter form on the right.
- You should receive the acquisition URL now in Marketo.
Fixes https://warthogs.atlassian.net/browse/WD-5437
> WD-5437 Add acquisition URL

- templates/templates/footer.html
Add our ICP number to the page footer, to unblock China-hosted mirroring of the site (ISDB-1338).
> Add ICP to footer template

- releases.yaml
- Copied the releases.yaml from [JP site](https://github.com/canonical/jp.ubuntu.com/blob/main/releases.yaml)
> Update releases for 22.04.4

- templates/blog/index.html
- Explicitly defined MIME type for blog feed as we do on [u.com
](https://github.com/canonical/ubuntu.com/blob/3774902ecc0c2d9356fcf8d68ee6fb16485f91a7/templates/blog/index.html#L5)
- This is an experimental fix for the bug(s) reported, I can't really think of a way to QA this locally without having access to Perkuto so just code review is needed
Issue flagged in MM, [see thread](https://chat.canonical.com/canonical/pl/78zxi9hdgtfspe311tczij7s3e)
> Define MIME type for blog rss feed

- templates/pricing/pro.html
- Increased the allowed storage capacity per node from '192TB' to '384TB'. More details can be found in [the issue](https://warthogs.atlassian.net/browse/WD-16414) (there is no copydoc)
- Open the demo: https://cn-ubuntu-com-739.demos.haus/pricing/pro
- Check that the change of  '192TB' to '384TB' have been applied
[[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]](https://warthogs.atlassian.net/browse/WD-16414)
> chore: Update ceph storage capacity information

- releases.yaml
Re-synchronize releases.yaml from ubuntu.com
https://github.com/canonical/ubuntu.com/blob/main/releases.yaml
- Open https://cn-ubuntu-com-742.demos.haus/download
- Confirm the section is updated to "Ubuntu Desktop 24.04.2 LTS" instead of .1
- Click `下载Ubuntu桌面版`
- Click the download (`下载 24.04.2`) link
- Confirm the download of "Ubuntu Desktop 24.04.2 LTS" starts
[WD-19543](https://warthogs.atlassian.net/browse/WD-19543)
[WD-19543]: https://warthogs.atlassian.net/browse/WD-19543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  Re-synchronize releases.yaml for 24.04.2 download links

- .github/workflows/live-links.yml
- Fix the typo where a wrong repository is shown
- Add URL for vimeo videos that should not be checked (similar to how it works for ubuntu.com)
> Adjust live-links GH action configuration

- releases.yaml
- Update desktop releases
- Go to https://cn-ubuntu-com-773.demos.haus/download/desktop
- Make sure 24.04.3 and 25.04 are listed
- Download both to make sure the download links work
[WD-2058](https://warthogs.atlassian.net/browse/WD-27058)
[WD-2058]: https://warthogs.atlassian.net/browse/WD-2058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-277058] chore: Update releases
